### ISSUE TITLE
The upload was successful, but the result was a failure.

### ISSUE THREAD

**Issue by d1210182010** [moom0o/PhotoSphereStudio#12]
Hi, 

Thank you for developing this nice open source tool! StreetView Studio is driving me crazy.

I just uploaded a 360 photo and got a [map URL](https://www.google.com/maps/@0,0,0a,90y,90t/data=!3m5!1e1!3m3!1sAF1QipOqMTMjOjd3zW--Otqq9AWA5RWxGXfwPMNpGK2H!2e10!3e12?entry=ttu) that didn't seem to work.
![image](https://github.com/moom0o/PhotoSphereStudio/assets/8273997/a9e53e12-608e-474d-ab5b-909ce109a397)

Is there a problem with the metadata of my 360 photo ([LINK](https://drive.google.com/file/d/1XqyxR5Smsgp6LawWLMby8iFiZIyBxal4/view?usp=sharing)) , or is uploading them via streetviewpublish API no longer working?

**Comment by moom0o** [comment]
Possibly try uploading again? It worked on my own account. Just remember that you will need to wait probably 10 minutes atleast, and then open it in an incognito tab to see the result.

**Comment by d1210182010** [comment]
It worked!
It does look like it would take a while to get the maps synchronized. Thank you for your help.

**Comment by d1210182010** [comment]
It worked!
It does look like it would take a while to get the maps synchronized. Thank you for your help.
