### ISSUE TITLE
Question: is google no longer showing the "blue dot" for new photos?

### ISSUE THREAD

**Issue by germanger** [moom0o/PhotoSphereStudio#17]
Since Google removed the upload feature from Streetview App, I've been using your site (https://maps.moomoo.me) and it has been working fine

But in the last uploads I've noticed that Google doesn't show the "blue dot" while dragging the streetview icon, even though the spherical photo is indeed there

Eg:
![image](https://github.com/user-attachments/assets/9edddec1-a67c-40c2-8a7c-e27ddc301c41)

As you can see, if I drag the streetview icon, a square thumb is shown but the blue dot is not shown

Is google now also deprecating the entire feature? I fkn hate them.

**Comment by milanomaster** [comment]
It can take about a good day (or two?) for the dot to appear on the map, unless they've changed it this week. Will try for myself soon too again

**Comment by germanger** [comment]
They finally appeared! sorry
